name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_run:
    workflows:
      - "Auto Tag"
    types:
      - completed

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyinstaller and build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          pip install setuptools wheel

      - name: Build Windows .exe
        run: |
          pyinstaller --onefile --name unitconverter app.py

      - name: Upload .exe to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/unitconverter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install py2app
        run: |
          python -m pip install py2app

      - name: Create setup.py
        run: |
          echo "from setuptools import setup" > setup.py
          echo "APP = ['app.py']" >> setup.py
          echo "OPTIONS = {'argv_emulation': True}" >> setup.py
          echo "setup(app=APP, options={'py2app': OPTIONS}, setup_requires=['py2app'])" >> setup.py
          cat setup.py  # Debug: Output setup.py content
          ls -la  # List directory to confirm setup.py is there

      - name: Build macOS .app
        run: python setup.py py2app

      - name: Zip .app bundle
        run: |
          cd dist
          zip -r unitconverter-mac.zip *.app

      - name: Upload .app to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/unitconverter-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tkinter
        run: |
          sudo apt-get install python3-tk

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile --name unitconverter app.py

      - name: Debug- List dist folder
        run: ls -la dist/

      - name: Create Desktop Entry for AppImage
        run: |
          mkdir -p AppDir/usr/share/applications
          echo "[Desktop Entry]
          Type=Application
          Name=UnitConverter
          Exec=unitconverter
          Icon=unitconverter
          Categories=Utility;" > AppDir/usr/share/applications/unitconverter.desktop

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp dist/unitconverter AppDir/usr/bin/
          chmod +x AppDir/usr/bin/unitconverter

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage AppDir unitconverter-x86_64.AppImage

      - name: Upload AppImage to Release
        uses: softprops/action-gh-release@v1
        with:
          files: unitconverter-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
